---
# brickburg/linuxrouter/roles/interfaces/handlers/main.yml

- name: 'Daemon reload'
  systemd:
    daemon_reload: true

- name: 'Trigger udev'
  systemd_service:
    name: systemd-udev-trigger
    state: restarted

- name: 'Reload networkd'
  shell:
    cmd: 'networkctl reload'

- name: 'Restart timesyncd'
  systemd_service:
    name: systemd-timesyncd
    state: restarted
  listen: [ 'Reload networkd' ]

- name: 'Restart resolved'
  systemd_service:
    name: systemd-resolved
    state: restarted
  listen: [ 'Reload networkd' ]

- name: 'Restart wpa_supplicant'
  shell:
    cmd: 'systemctl restart --all "wpa_supplicant@*.service"'

- name: 'Restart hostapd'
  shell:
    cmd: 'systemctl restart --all "hostapd-lr@*.service"'
