---
# brickburg/linuxrouter/roles/dhcp/tasks/main.yml

- name: Install dnsmasq
  apt:
    force_apt_get: yes
    name:
      - dnsmasq

- name: Configure dnsmasq service
  ansible.builtin.lineinfile:
    path: /etc/default/dnsmasq
    regexp: '{{item.p}}'
    line: '{{item.v}}'
  loop:
    - { p: '^ENABLED=', v: 'ENABLED=1' }
    - { p: '^IGNORE_RESOLVCONF=', v: 'IGNORE_RESOLVCONF=yes' }
    - { p: '^DNSMASQ_EXCEPT=', v: 'DNSMASQ_EXCEPT="lo"' }
  notify:
    - 'Daemon reload'
    - 'Restart dnsmasq'

- name: dnsmasq config
  template:
    src: files/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: u=rw,go=r
  notify:
    - 'Restart dnsmasq'
