---
# roles/selfsignedcert/tasks/main.yml

- name: Install python dependencies
  apt:
    force_apt_get: yes
    name:
      - python3-cryptography

- name: Create private key for CA certificate
  community.crypto.openssl_privatekey:
    path: "{{selfsigned_cakeypath}}"
    type: RSA
    size: 4096
    owner: root
    group: root
    mode: u=rw,go=-

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr:
    path: "{{selfsigned_cacsrpath}}"
    privatekey_path: "{{selfsigned_cakeypath}}"
    country_name: DE
    locality_name: Lower Saxony
    organization_name: IAC
    organizational_unit_name: Perrys Ansible Apply CA
    common_name: Perrys Ansible Apply CA
    email_address: no-reply@example.com
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
    owner: root
    group: root
    mode: u=rw,go=-
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{selfsigned_cacertpath}}"
    csr_path: "{{selfsigned_cacsrpath}}"
    privatekey_path: "{{selfsigned_cakeypath}}"
    provider: selfsigned
    selfsigned_not_after: "+3650d"
    selfsigned_not_before: "-1d"
    owner: root
    group: root
    mode: u=rw,go=r

- name: Create private key for self-signed certificate
  community.crypto.openssl_privatekey:
    path: "{{selfsigned_keypath}}"
    type: RSA
    size: 4096
    owner: root
    group: root
    mode: u=rw,go=-

- name: Create SAN list
  set_fact:
    newsanlist: "{{ ([selfsigned_name]+selfsigned_names) | map('regex_replace', '^', 'DNS:') }}"

- name: Create CSR for self-signed certificate
  community.crypto.openssl_csr:
    path: "{{selfsigned_certcsrpath}}"
    privatekey_path: "{{selfsigned_keypath}}"
    subject_alt_name: "{{newsanlist}}"
    common_name: "{{selfsigned_name}}"
    country_name: DE
    locality_name: Lower Saxony
    organization_name: IAC
    organizational_unit_name: Perrys Ansible Router
    email_address: no-reply@example.com
    owner: root
    group: root
    mode: u=rw,go=-
  register: csr

- name: Sign certificate with CA
  community.crypto.x509_certificate:
    path: "{{selfsigned_certpath}}"
    csr_path: "{{selfsigned_certcsrpath}}"
    provider: ownca
    ownca_path: "{{selfsigned_cacertpath}}"
    ownca_privatekey_path: "{{selfsigned_cakeypath}}"
    ownca_not_after: +3600d
    ownca_not_before: "-12h"
    owner: root
    group: root
    mode: u=rw,go=r
  register: certificate

- name: Copy CA into trust store for Debian/Ubuntu systems
  copy:
    remote_src: true
    src: "{{selfsigned_cacertpath}}"
    dest: "/usr/local/share/ca-certificates/{{selfsigned_cacertpath|basename}}"
    owner: root
    group: root
    mode: u=rw,go=r
  register: cacopy

- name: Regenerate trust store for Debian/Ubuntu systems
  shell:
    chdir: /
    executable: /bin/bash
    cmd: |
      update-ca-certificates
  when: cacopy.changed

- name: Generate a 2048 bit dhparam
  community.crypto.openssl_dhparam:
    path: "{{selfsigned_dhparampath}}"
    size: 2048
