---
- name: Apply lirou configuration
  hosts: lirounodes

  vars_files:
    - /etc/lirou/config.yml

  tasks:

    - name: Prepare Parameters
      include_role:
        name: brickburg.linuxrouter.params
        apply: { tags: [ always ] }
      tags: [ always ]

    - name: Configure OS
      include_role:
        name: brickburg.linuxrouter.osconfig
        apply: { tags: [ system ] }
      tags: [ system ]

    - name: Configure PC Engines APU Board
      include_role:
        name: brickburg.linuxrouter.hardware_pcengines
        apply: { tags: [ system ] }
      when: "ansible_board_vendor == 'PC Engines'"
      tags: [ system ]

    - name: Install Software
      include_role:
        name: brickburg.linuxrouter.software
        apply: { tags: [ system, software ] }
      tags: [ system, software ]

    - name: Setup serial interface
      include_role:
        name: brickburg.linuxrouter.serial
        apply: { tags: [ system ] }
      tags: [ system ]

    - name: Setup Interfaces
      include_role:
        name: brickburg.linuxrouter.interfaces
        apply: { tags: [ interfaces ] }
      tags: [ interfaces ]

    - name: Setup Interface Events
      include_role:
        name: brickburg.linuxrouter.interfaceevents
        apply: { tags: [ interfaces, events ] }
      tags: [ interfaces, events ]

    - name: Setup DHCP
      include_role:
        name: brickburg.linuxrouter.dhcp
        apply: { tags: [ interfaces, services, dhcp ] }
      tags: [ interfaces, services, dhcp ]

    - name: Setup Firewall
      include_role:
        name: brickburg.linuxrouter.firewall
        apply: { tags: [ firewall ] }
      tags: [ firewall ]

    - name: Setup webservices
      include_role:
        name: brickburg.linuxrouter.webservices
        apply: { tags: [ services, webservices ] }
      tags: [ services, webservices ]
